name: Compile LaTeX document
on: [push, pull_request]

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: report
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
      
    - name: List files in the report directory
      run: ls -R
      
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: project_report.tex
        working_directory: report
      
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: Compiled PDF
        path: project_report.pdf
